### ISSUE TITLE
app.activate() should be removed

### ISSUE THREAD

**Issue by robertforeman** [mitxp/HbbTV-Testsuite#30]
base.js:21 calls app.activate()

In the OIPF DAE specification, the Application object has an activateInput() method. There is no activate() method, although activate() is mentioned in v1.2 of the DAE due to a spelling mistake, which was fixed in v2.3.

However, activateInput() is not included in any version of HbbTV, so this line should be deleted.

**Comment by mitxp** [comment]
this is for HbbTV 0.5 backwards-compliance. It will throw an ignored exception on HbbTV 1.x devices, which does not cause any harm. Please ignore this line. We will want to keep it as it is because otherwise, we'll completely exclude those old devices from the test suite.
