### ISSUE TITLE
HTML5 video stop()

### ISSUE THREAD

**Issue by xiaosongLin123** [mitxp/HbbTV-Testsuite#32]
Hello Guys,
      About Testsuite release: 2.0.2 (20150727), there is one case named "Hbbtv 1.3 HTML5 video".
      In this case, an stop() method is used to stop the html5 video, but according to W3C standard, there is no stop() method.  I think "oldvideo.paused(); oldvideo.src= ' '  " shoud be used for stopping a HTML5 Video.
    Could you guys help to check it ?

**Comment by mitxp** [comment]
This code is only for stopping the broadcast video on the switch back from HTML5 to broadcast. Added some comments to clarify this. It's not part of the TC as it is surrounded by a try ... catch.
