### ISSUE TITLE
 HbbTV 1.3 CSS3 animation is not backwards compatible

### ISSUE THREAD

**Issue by xiaosongLin123** [mitxp/HbbTV-Testsuite#33]
Hi Mitxperts，
   we have analysed the latest MIT-Xperts test cases, now facing an issue with
       http://itv.mit-xperts.com/hbbtvtest/animation/ 
        Test 6: HbbTV 1.3 CSS3 animation

from source:
animation: spin 2s linear infinite; 
is not backwards compatible, e.g. it is not supported in chrome v40, but working with chrome v44. 

please add backwards compatible parts like:
<style rel="stylesheet" type="text/css">
.cssrotate {
  animation: spin 2s linear infinite;
  -webkit-animation: spin 2s linear infinite;     /*Webkit*/
}
@-webkit-keyframes spin { 100% { transform:rotate(360deg); } }    /*Webkit*/
@keyframes spin { 100% { transform:rotate(360deg); } }

Thanks.

**Comment by mitxp** [comment]
Hi,
the "-webkit" CSS rules are not covered by HbbTV. As this is a HbbTV testsuite, we cannot add these rules to our testsuite.
Please understand that these are HbbTV 1.3 (a.k.a HbbTV 2.0) tests that you do not need to pass if you do not claim to support this version of HbbTV.
