### ISSUE TITLE
getSIDescriptors() return null if descriptorTagExtension and privateDataSpecifier does not exist

### ISSUE THREAD

**Issue by liuxunjxys** [mitxp/HbbTV-Testsuite#34]
Hi MIT-xperts,

please refer to latest OIPF DAE spec in chapter "7.16.2.4 DVB-SI extensions to Programme", it says "If the descriptor specified by descriptorTag and (optionally) descriptorTagExtension and privateDataSpecifier does not exist, this method SHALL return null"

so hbbtv MIT testcase at EIT events/Present event descriptors (HbbTV 1.2) the javascript write in this way:
try {
    descr = evt.getSIDescriptors(descrcodes[0]);
  } catch (e2) {
    showStatus(false, 'Retrieval of descriptors failed');
    return;
  }

if (!descr || descr.length<1) {
    showStatus(false, 'No descriptor returned');
    return;
  }

actually descr return null.

**Comment by mitxp** [comment]
Yes, but we know that the test stream contains the descriptor, so "null" is an invalid result and the test needs to fail in this case.
