### ISSUE TITLE
Content-Type in <meta> tag

### ISSUE THREAD

**Issue by robertforeman** [mitxp/HbbTV-Testsuite#36]
The meta tag for XHTML apps appears as

`<meta http-equiv="content-type" content="Content-Type: application/vnd.hbbtv.xhtml+xml; charset=UTF-8" />`

but should be

`<meta http-equiv="Content-Type" content="application/vnd.hbbtv.xhtml+xml; charset=UTF-8" />`

(i.e. the string "Content-Type: " should be only in the http-equiv attribute and not in the content attribute)

This affects:

- base.php
- appmanager/preferdsmcc.html
- imuxcfg/dsmcc/index.html
- imuxcfg/dsmcc/preferdsmcc.html

**Comment by mitxp** [comment]
Wow, this is embarassing!
Thanks for the hint, it should be fixed now.

Unfortunately, I currently cannot build a new stream right now (for the updated DSMCC's), but I hope I will be able to do that soon.

**Comment by mitxp** [comment]
New stream is generated:
http://download.mit-xperts.com/hbbtvts201605.zip
