### ISSUE TITLE
Automation PIN code uses VK_0-VK_9 but app does set keyset mask to use it

### ISSUE THREAD

**Issue by mpiechaczek** [mitxp/HbbTV-Testsuite#37]
Few days ago automation support was added.

Code that handles automation PIN code handles VK_0-VK_9 keys (https://github.com/mitxp/HbbTV-Testsuite/blob/master/index.php line 40), but application does not set proper keyset to handle numeric keys (i.e. Keyset.NUMERIC)

Please update initApp() in https://github.com/mitxp/HbbTV-Testsuite/blob/master/base.js to include Keyset.NUMERIC, i.e. call
  setKeyset(0x1+0x2+0x4+0x8+0x10+0x100);
instead of:
  setKeyset(0x1+0x2+0x4+0x8+0x10);

**Comment by mitxp** [comment]
Thanks for the hint, I fixed it. Please note that the automation is neither tested nor functional yet.
