### ISSUE TITLE
Incorrect parental rating threshold value displayed

### ISSUE THREAD

**Issue by bukington** [mitxp/HbbTV-Testsuite#40]
In parental control test, the current threshold is displayed using "document.getElementById('pcmgr').parentalRatingSchemes.getParentalRatingScheme('dvb-si').threshold + 3".
HbbTV 2.0.1 specification states that in ParentalRating class, the name property should contain the Age:
'For instances with a scheme of "dvb-si", the name property is a string containing an age in years, encoded as a decimal in the range "4" to "18" inclusive.'

So I think that you should not add 3 to the value retrieved (as the value attribute should be the integer representation of the name attribute).

**Comment by mitxp** [comment]
Thanks for the valuable hint. I actually forgot to check HbbTV spec, I only looked at OIPF.
Test is fixed now.
