### ISSUE TITLE
Detect no parental rating threshold

### ISSUE THREAD

**Issue by dblachut-adb** [mitxp/HbbTV-Testsuite#41]
The following code should be updated to detect no threshold signalling:
```javascript
if (parseInt(rating.name)!=rating.value) {
      showStatus(false, 'Current threshold rating name is not string representation of value attribute');
      return;
}
```
From: https://github.com/mitxp/HbbTV-Testsuite/blob/master/parentalcontrol/index.php#L86

As per HbbTV 2.0.1 spec, no threshold can be signalled for 'dvb-si' scheme in the following way:
> **Table A.1, Notes for 7.9.2**
The threshold.value and threshold.name properties shall be undefined if the user has set no minimum age in the terminal's None parental control system (i.e. the user will never be requested for their PIN) and the threshold.scheme property is dvb-si.

**Comment by mitxp** [comment]
You are right. But I don't want an implementation to just set a dummy "undefined" value for any case. So (in my opinion) I would recommend to configure the TV accordingly to set a minimum age before running this test. I hope you agree. If not, please re-open.

**Comment by dblachut-adb** [comment]
What I meant was that the test fails for a valid case that is described directly in HbbTV specification. In my opinion it would be good to add another "if", because the validation "parseInt(rating.name)!=rating.value" does not cover it.
```javascript
if ("name" in rating && "value" in rating &&
    rating.name === undefined && rating.value === undefined) {
      showStatus(2, 'Current threshold is not set.');
      return;
}
if (parseInt(rating.name)!=rating.value) {
      showStatus(false, 'Current threshold rating name is not string representation of value attribute');
      return;
}
```
If the test assumes some precondition before running it would be good to add it to test description, but TBH I don't see a reason why the test should not cover more sections of the specification. I hope you share my opinion, I can make a pull request if this would be easier for you and if you agree.

**Comment by mitxp** [comment]
Hi, what do you think of the current solution as seen on http://itv.mit-xperts.com/hbbtvtest/parentalcontrol/ (not checked in yet because I'm waiting for your opinion). Please note: I explicitly wanted to avoid the showStatus(2, ...) as everybody ignores that kind of status messages and this could lead to bad/invalid implementations.

**Comment by dblachut-adb** [comment]
I think the current solution is much better, as the message describes the situation well. I am not sure if this should be reported as an error because this is a valid situation (that's why I used more neutral showStatus(2, ...)).

**Comment by mitxp** [comment]
Thanks. As explained previously, I don't want this test to pass (or even pass as undefined with status 2) with undefined rating values, as this would lead to implementations on many devices where always "undefined" is returned. Change is now officially checked in & released.

**Comment by dblachut-adb** [comment]
No problem, I understand, thank you for clarification.
