### ISSUE TITLE
HTML5 video test should keep the v/b alive after stop()

### ISSUE THREAD

**Issue by fvalleeHbbTV** [mitxp/HbbTV-Testsuite#43]
"HbbTV 2.0.1 specification introduced change about resource management (section A.2.1) between HTML5 media elements and broadcast video in way that application has to stop broadcast video before playing media through HTML5 media elements (unless there is synchronization involved)"
https://www.hbbtv.org/redmine/issues/6230

The statement in section A.2.1 is:

> An HTML5 media element shall not be able to obtain resources
 that are already in use either by an A/V control object 
or to present broadcast video (either by the HbbTV application through a video/broadcast object, or by the terminal 
when it is presenting broadcast content not under the control of
 a video/broadcast object). 

In the HTML5 video test page: 
http://itv.mit-xperts.com/hbbtvtest/html5vid/

in govid function, the video/broadcast is stopped then released. The terminal will take over broadcast video presentation. As the broadcast is playing, HTML5 video won't be able to reach the "potentially playing state" on devices not supporting the multi-decoder model.

To support HTML5 video presentation, the video broadcast should stop() and should not be released, or the app should be broadcast independent.

Let me know if I'm missing something.

**Comment by mitxp** [comment]
Interesting. I remember that there was/is a part of the spec saying that the terminal should go back to broadcast video presentation once the video/broadcast object is stopped (I actually remember "stopped" but you're saying "released"). Anyway, I quickly checked the specs, but I couldn't find anything. Could you please point me to that part of the specification?

Many thanks.

**Comment by fvalleeHbbTV** [comment]
When broadcast video presentation is under the control of the application, stop() is used to stop presenting the broadcast audio/video. 
release() method is used to return the control of video to the terminal :

> OIPF Release 2 Volume 5 DAE v2.3:
> H.2 Interaction with the video/broadcast and A/V Control objects
> "If the release() method is called on a video/broadcast object, or if the object is garbage collected, control of broadcast video presentation SHALL be returned to the OITF and video SHALL be re-scaled and re-positioned (if necessary)."

> OIPF Release 2 Volume 5 DAE v2.3:
>  7.13.1 The video/broadcast embedded object
Table 8: State transitions for the video/broadcast embedded object

If the broadcast video presentation is controlled by the terminal, I guess the broadcast audio/video is expected to be presented, even if I didn't find any explicit reference to this case in the specifications.

**Comment by mitxp** [comment]
I think you are right, even though this rises some discussion :)
This makes implementations for application developers really difficult. I know the test could be implemented differently (in a way that is more simple), but I want to keep app developers in mind, so I chose this implementation where I move away the old video/broadcast object and then stop it (but not release it) and after that instantiate the video element:
http://itv.mit-xperts.com/hbbtvtest/html5vid/i.php

Could you please have a look and tell me if the new test is valid before I publish it under the existing URL?

**Comment by fvalleeHbbTV** [comment]
yeah I understand it's not really convenient for app developers, actually you're not the only one to complain about it.

> We changed the resource manangement for HTML5 element to fail presenting media when in use for presenting broadcast.

>According to feedback from one of ARD's app developer this was a bad idea.
His opinion and I agree is: a media object should always be able to take resources when there is no v/b object in use.
(from HbbTV redmine 6848).

I tested your page, and it's working. thanks.

I've an issue with my implementation as the application is not waiting for the video/broadcast state to be updated to Stopped after the stop() - i.e. when he html5 video play() is called we have not received yet the event confirming the broadcast playback is actually stopped. I think i've to handle this case somehow as I don't think applications are actually going to wait for the playStateChanged "stopped" event before playing the broadband video.

**Comment by mitxp** [comment]
Indeed. I'll have to change all of our applications, too.

Glad you see no issues in the test anymore. Did a minor modification (there was an issue when you tried to start the video/broadcast twice without playing an html5 vid in between) and published it. Closing issue.

(and, by the way, thanks for reporting the issue, even though it was no fun for both sides, but sometimes the specification is not very nice).

**Comment by fvalleeHbbTV** [comment]
good. mit-xperts is quite useful, thanks for your efforts!
