### ISSUE TITLE
http://itv.mit-xperts.com/hbbtvtest/clientssl/    -> Load image via HTTPS

### ISSUE THREAD

**Issue by cy-hello** [mitxp/HbbTV-Testsuite#47]
find cannot load iamge,and test failed:

https://itv.mit-xperts.com/hbbtvtest/logo.png  show net::ERR_INSECURE_RESPONSE

![649687ebdc0c26366bc8b74fa3871e4](https://user-images.githubusercontent.com/20079188/93364229-e29f2300-f87a-11ea-985f-88f3351c6723.jpg)

Is it because of missing certificates ？

**Comment by mitxp** [comment]
Seems to be because the CA certificate is missing (not installed on your device).

**Comment by cy-hello** [comment]
Can send CA certificate to "caoyang190@gmail.com"  ?
thanks

**Comment by cy-hello** [comment]
I have resolved it ,  https://itv.mit-xperts.com/hbbtvtest/logo.png  -> use  devtools' security to find CA,
and test pass
