### ISSUE TITLE
Application Manager tests

### ISSUE THREAD

**Issue by giorgos-epitropou-obs** [mitxp/HbbTV-Testsuite#48]
Hi, one question about the application manager test; does the test require that there should be a broadcast service already started /playing, before destroyApplication is called?

**Comment by mitxp** [comment]
There is no possiblity that the broadcast service is not running/playing when destroyApplication is called.
The whole testsuite is started from the broadcast service. Please also see the Wiki https://github.com/mitxp/HbbTV-Testsuite/wiki (chapter "Running the test suite").
