### ISSUE TITLE
Content on Dolby servers is missing

### ISSUE THREAD

**Issue by zooltar** [mitxp/HbbTV-Testsuite#49]
Hi,

Test cases located under **DOLBY video format / AVComponents** fetch content from remote, dolby server. Trying to access DASH manifest returns HTTP 404 error.

Regards,
Przemysław Mazur

**Comment by mitxp** [comment]
Cannot reproduce this. I checked all DASH mpd manifest URLs from all tests and they all load OK without any HTTP 404 errors.
In case you re-open this issue, please tell me the exact test and the URL that creates the error.
