### ISSUE TITLE
Dash live (geoblock)

### ISSUE THREAD

**Issue by giorgos-epitropou-obs** [mitxp/HbbTV-Testsuite#50]
Hello,
what is the expected behavior for Streaming video/audio formats/MPEG DASH live (Geoblock) test?
I tried to wget/curl the manifest but i got a 403 http error.

`wget http://rbb-dash-berlin.akamaized.net/dash/live/2017826/rbb_berlin/manifest.mpd
--2021-12-06 14:12:20--  http://rbb-dash-berlin.akamaized.net/dash/live/2017826/rbb_berlin/manifest.mpd
Resolving rbb-dash-berlin.akamaized.net (rbb-dash-berlin.akamaized.net)... 212.205.126.169, 212.205.126.34, 2a02:582:a00::d4cd:7ea9, ...
Connecting to rbb-dash-berlin.akamaized.net (rbb-dash-berlin.akamaized.net)|212.205.126.169|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-12-06 14:12:20 ERROR 403: Forbidden.
`

**Comment by mitxp** [comment]
This is the expected result if you are not in Germany.
When requested via a VPN in Germany, you will get the DASH Stream.
