### ISSUE TITLE
HTML5 Video Test case problem

### ISSUE THREAD

**Issue by bravo1003** [mitxp/HbbTV-Testsuite#53]
Hi, I've encounter an possible issue but not sure if it is the intended behavior.

When entering HTML5 Video test case and go through step 1~3 I've found out that video/broadcast's video hole remains while html5 video is already moved to the lower right according to step 3.

I understand that the simplified behavior from step 1 to step 2 is as followed
1. video/broadcast.bindToCurrentChannel()
2. video/broadcast.stop()
3. html5.play()

I don't see in html5vid.index about setting visibility of such video/broadcast and by oipf spec if video/broadcast is in stopped state `The content of the video/broadcast object shall be an opaque black rectangle`.  Thus the opaque black punch hole is remained. Why don't we leave video/broadcast in `unrealized` state so such punch hole would disappear?

It just seem a bit odd to me that there's an unused punch hole for video/broadcast there when executing steps 2~8.
Could you help to answer if this is intended behavior?

Regards,
John

**Comment by mitxp** [comment]
I am very sorry this took so long, I somehow forgot this issue was still open.
Yes, you are absolutely right, and I just changed the test to set the broadcast video to hidden. If this was not what you had in mind, please let me know and re-open this issue.
