### ISSUE TITLE
mp3radio.php not accessable

### ISSUE THREAD

**Issue by BrickOzp** [mitxp/HbbTV-Testsuite#54]
The test case Streaming video/audio formats -> Audio stream (MP3) does not work since the referenced stream http://itv.mit-xperts.com/hbbtvtest/media/mp3radio.php will not load. The Connection was reset.

http**s**://itv.mit-xperts.com/hbbtvtest/media/mp3radio.php works though.

**Comment by mitxp** [comment]
Just checked: http URL works fine. No connection reset whatsoever. Maybe a HSTS issue? (even though our web server does not use HSTS)
Try it with a simple cURL and you will see it works fine:
curl --output /dev/null http://itv.mit-xperts.com/hbbtvtest/media/mp3radio.php
